# Generated by Django 5.2.6 on 2026-02-24 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_chatmessage_image_chatmessage_video_and_more'),
        ('user', '0003_profile_photo_data'),
    ]

    operations = [
    ]
