# Generated by Django 5.2.5 on 2026-03-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_merge_20260224_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='chat/voices/'),
        ),
    ]
